INSERT INTO MALWAREURL VALUES(1, 'test');
INSERT INTO MALWAREURL VALUES(2, 'test');
INSERT INTO MALWAREURL VALUES(3, 'test');
INSERT INTO MALWAREURL VALUES(4, 'test');
INSERT INTO MALWAREURL VALUES(5, 'test');
INSERT INTO MALWAREURL VALUES(6, 'test');
